navsat_transform_node:
  ros__parameters:
    frequency: 50.0
    delay: 3.0
    magnetic_declination_radians: 0.0
    yaw_offset: 3.14159265359
    zero_altitude: true
    broadcast_cartesian_transform: false
    broadcast_utm_transform_as_parent_frame: false
    publish_filtered_gps: false
    use_odometry_yaw: false
    wait_for_datum: false
